package com.aercs.entity;

public enum RelatedOffice {
    QUALITY_ASSURANCE_OFFICE,
    RESEARCH_OFFICE,
    EXTENSION_OFFICE,
    REGISTRARS_OFFICE,
    LIBRARY,
    STUDENT_AFFAIRS_OFFICE,
    GUIDANCE_OFFICE,
    HUMAN_RESOURCE_OFFICE,
    FACILITIES_MANAGEMENT_OFFICE,
    FINANCE_OFFICE,
    CLINIC,
    COLLEGE_OF_COMPUTER_STUDIES,
    COLLEGE_OF_ENGINEERING_AND_ARCHITECTURE,
    COLLEGE_OF_NURSING,
    COLLEGE_OF_MANAGEMENT_BUSINESS_AND_ACCOUNTANCY,
    COLLEGE_OF_ARTS_AND_SCIENCES,
    COLLEGE_OF_EDUCATION
}
